### PR TITLE
Update dotnet (add versions +fix)

### LINKED ISSUE #705: osu! errors out when installing
I'm confused if this is a problem with Wine, or with POL, or even with my system,
When I install osu! normally through POL5, this shows up: 
https://imgur.com/a/zr3PZxA
PB: https://pastebin.com/9BRYEnai
This happens system-wide so I am a bit confused why it doesn't work in the first place.

System: Arch x86_64

### PR DESCRIPTION
**Pull request by ImperatorS79**
The modification are mainly to be closer to winetricks source (since those verbs come from there).

Added dotnet472, which will allow osu to install and fix #705 (upcoming PR), and also maybe paint.net.

Edit: [https://github.com/Winetricks/winetricks/issues/971](https://github.com/Winetricks/winetricks/issues/971) This could be interesting to implement, for example Space engineers.

### CODE REVIEW

File: Engines/Wine/Verbs/dotnet40/script.js [hunk 1]
```diff
@@ -3,12 +3,21 @@ include(["engines", "wine", "plugins", "override_dll"]);
...
 * Verb to install .NET 4.0
 * @returns {Wine} Wine object
 */
 Wine.prototype.dotnet40 = function () {
+    if (this.architecture = "amd64") {
+        print(tr("This package ({0}) may not fully work on a 64-bit installation. 32-bit prefixes may work better.", "dotnet40"));
+    }
+
+    var OSVersion = this.windowsVersion();
+    if (OSVersion == null)
```
Comment (plata) [inline Engines/Wine/Verbs/dotnet40/script.js]: Can this actually happen?

File: Engines/Wine/Verbs/dotnet40/script.js [hunk 2]
```diff
@@ -3,12 +3,21 @@ include(["engines", "wine", "plugins", "override_dll"]);
...
 /**
 * Verb to install .NET 4.0
 * @returns {Wine} Wine object
 */
 Wine.prototype.dotnet40 = function () {
+    if (this.architecture = "amd64") {
+        print(tr("This package ({0}) may not fully work on a 64-bit installation. 32-bit prefixes may work better.", "dotnet40"));
+    }
+
+    var OSVersion = this.windowsVersion();
```
Comment (plata) [inline Engines/Wine/Verbs/dotnet40/script.js]: Should be `osVersion`.

File: Engines/Wine/Verbs/dotnet40/script.js [hunk 3]
```diff
@@ -30,14 +36,22 @@ Wine.prototype.dotnet40 = function () {
     this.wizard().wait(tr("Please wait while {0} is installed...", ".NET Framework 4.0"));
     this.run(setupFile, [setupFile, "/q", "/c:\"install.exe /q\""], null, false, true);
 
+    this.wizard().wait(tr("Please wait ..."));
```
Comment (plata) [inline Engines/Wine/Verbs/dotnet40/script.js]: Should be "Please wait..." (no space before ellipsis). Also below.

File: Engines/Wine/Verbs/dotnet40/script.js [hunk 4]
```diff
@@ -30,14 +36,22 @@ Wine.prototype.dotnet40 = function () {
...
     this.overrideDLL()
         .set("native", ["mscoree"])
         .do();
 
-    this.wizard().wait(tr("Please wait..."));
-    this.run("reg", ["add", "HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full", "/v", "Install", "/t", "REG_DWORD", "/d", "0001", "/f"], null, false, true);
-    this.wizard().wait(tr("Please wait..."));
-    this.run("reg", ["add", "HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full", "/v", "Version", "/t", "REG_SZ", "/d", "4.0.30319", "/f"], null, false, true);
+    this.wizard().wait(tr("Please wait ..."));
+    this.run("reg", ["add", "HKLM\\Software\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full", "/v", "Install", "/t", "REG_DWORD", "/d", "0001", "/f"], null, false, true);
```
Comment (plata) [inline Engines/Wine/Verbs/dotnet40/script.js]: Can't you use the regedit plugin for the registry operations you need?

File: Engines/Wine/Verbs/dotnet46/script.json [hunk 5]
```diff
@@ -0,0 +1,14 @@
+{
+    "scriptName"                 : ".NET 4.6",
+    "id"                         : "dotnet46",
+    "compatibleOperatingSystems" : [
+        "MACOSX",
+        "LINUX"
+    ],
+    "testingOperatingSystems" : [
```
Comment (plata) [inline Engines/Wine/Verbs/dotnet46/script.json]: Why testing?

File: Engines/Wine/Verbs/dotnet461/script.js [hunk 6]
```diff
@@ -2,14 +2,21 @@ include(["engines", "wine", "engine", "object"]);
...
 include(["utils", "functions", "filesystem", "files"]);
-include(["engines", "wine", "verbs", "dotnet452"]);
+include(["engines", "wine", "verbs", "dotnet46"]);
 
 /**
 * Verb to install .NET 4.6.1
 * @returns {Wine} Wine object
 */
 Wine.prototype.dotnet461 = function () {
+    if (this.architecture = "amd64") {
```
Comment (plata) [inline Engines/Wine/Verbs/dotnet461/script.js]: `=`? I think you want `===` or at least `==`.

File: Engines/Wine/Verbs/dotnet40/script.js (hunk 1 above)
Comment (ImperatorS79) [reply Engines/Wine/Verbs/dotnet40/script.js]: Yes, when you execute the script in a preInstall without this condition, the os version set at the end of the script does not work because the version is null.

**Comment by Zemogiter** [comment]
You must replace `=` with `==`.

File: Engines/Wine/Verbs/dotnet40/script.js (hunk 1 above)
Comment (qparis) [reply Engines/Wine/Verbs/dotnet40/script.js]: You want to use a windows windows only during the installation, correct? 
If so, you can ommit this check since a recent commit I have done. In fact, now, windowsVersion(null) will unset the setting

**Comment by ImperatorS79** [comment]
@qparis I have the same problem than in #825 with the registry: from the GUI of regedit with a .reg it works, with wine by command line or in the script it does not :thinking:.

File: Engines/Wine/Verbs/dotnet40/script.js [hunk 7]
```diff
@@ -30,14 +33,28 @@ Wine.prototype.dotnet40 = function () {
...
-    this.wizard().wait(tr("Please wait..."));
-    this.run("reg", ["add", "HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full", "/v", "Version", "/t", "REG_SZ", "/d", "4.0.30319", "/f"], null, false, true);
+    var regeditFileContent = "REGEDIT4\n"                                                                      +
+                             "\n"                                                                              +
+                             "[HKEY_LOCAL_MACHINE\\Software\\Microsoft\\NET Framework Setup\\NDP\\v4\\Full]\n" +
+                             "\"Install\"=dword:0001\n"                                                        +
+                             "\"Version\"=\"4.0.30139\"";
+
+    this.regedit().patch(regeditFileContent);
+    print(regeditFileContent);
```
Comment (madoar) [inline Engines/Wine/Verbs/dotnet40/script.js]: I guess this is a debug print?

File: Engines/Wine/Verbs/dotnet40/script.js [hunk 8]
```diff
@@ -1,14 +1,20 @@
...
-include(["utils", "functions", "filesystem", "files"]);
+include(["engines", "wine", "plugins", "regedit"]);
+include(["engines", "wine", "plugins", "windows_version"]);
 
 /**
 * Verb to install .NET 4.0
 * @returns {Wine} Wine object
 */
 Wine.prototype.dotnet40 = function () {
+    if (this.architecture == "amd64") {
```
Comment (madoar) [inline Engines/Wine/Verbs/dotnet40/script.js]: Are you sure about `this.architecture` and not `this.architecture()`? `Wine.prototype.architecture` is a function, see:
https://github.com/PhoenicisOrg/scripts/blob/f7c70527bc69dab5f0aa8bef49fda2674d9e6575/Engines/Wine/Engine/Object/script.js#L29-L43

File: Engines/Wine/Verbs/dotnet45/script.js [hunk 9]
```diff
@@ -2,21 +2,18 @@ include(["engines", "wine", "engine", "object"]);
...
 /**
 * Verb to install .NET 4.5
 * @returns {Wine} Wine object
 */
 Wine.prototype.dotnet45 = function () {
-
-    if (this.architecture() == "amd64") {
-        throw "{0} cannot be installed in a 64bit wine prefix!".format("dotnet45");
+    if (this.architecture == "amd64") {
+        print(tr("This package ({0}) may not fully work on a 64-bit installation. 32-bit prefixes may work better.", "dotnet45"));
```
Comment (madoar) [inline Engines/Wine/Verbs/dotnet45/script.js]: Why `print(...)` and not `this.wizard().message(...)`?

Comment (ImperatorS79) [reply Engines/Wine/Verbs/dotnet45/script.js]: Well, I do not know if it is relevant to display this when you are installing an application. But sure it should be done when installing the verb from the container tab.

File: Engines/Wine/Verbs/dotnet40/script.js (hunk 8 above)
Comment (madoar) [reply Engines/Wine/Verbs/dotnet40/script.js]: This needs to be changed in the other files too.

File: Engines/Wine/Verbs/dotnet45/script.js (hunk 9 above)
Comment (ImperatorS79) [reply Engines/Wine/Verbs/dotnet45/script.js]: Yes, but I wonder if showing such a warning when installing an app will not confuse people like "this does not seem really stable". I mean the script should be tested so this warning is meaningless when the verb is called inside an application script.

Comment (madoar) [reply Engines/Wine/Verbs/dotnet45/script.js]: Then why add the warning at all?

Comment (ImperatorS79) [reply Engines/Wine/Verbs/dotnet45/script.js]: Just as a reminder, for people wanting to use the verb (I think I will add it as a message in the verb implementation).

Comment (madoar) [reply Engines/Wine/Verbs/dotnet45/script.js]: @plata @qparis what do you think? How should we print warnings? Via `print(...)` or `this.wizard().message(...)`? I think we need to have a standard for this.

Comment (plata) [reply Engines/Wine/Verbs/dotnet45/script.js]: Depends if the user can react on it. In this case, showing the message in the wizard would mean that a user installing a script which uses this verb would see the message. What is he supposed to do about it (except opening an issue on GitHub asking if this is alright)?

Comment (madoar) [reply Engines/Wine/Verbs/dotnet45/script.js]: Then why do we show the message at all? Everything we print with `print` is only written in the terminal, which is not really a place where I would look for warning messages as a user.

Maybe we can add an icon with an `?` or an `!` which shows the warning when hovering over it.
This would still add the warning to the UI but hide it to prevent the user from overreacting?

Comment (plata) [reply Engines/Wine/Verbs/dotnet45/script.js]: If it's in the terminal, we should get it as part of a potential error report (which is IMHO the only use case for this).

**Comment by ImperatorS79** [comment]
I think I will end up only modifying dotnet40 and dotnet45, because all the others seems completely broken now (which is strange since I made dotnet472 works some times ago...).

**Comment by Zemogiter** [comment]
In `Remove Mono` the id have a upper case

**Comment by ImperatorS79** [comment]
I have seen ;-).

**Comment by ImperatorS79** [comment]
@Zemogiter osu! should install without any problem. The bug came from the fact that, when @qparis modified ´wine.windowsVersion()` to delete `[HKEY_CURRENT_USER\\Software\\Wine]` when calling `wine.windowsVersion(null)`, this also deleted dll overrides information !

**Comment by plata** [comment]
@qparis have you been aware of this effect? Is it what you intended/how it should behave?

**Comment by qparis** [comment]
> @qparis have you been aware of this effect? Is it what you intended/how it should behave?

No, it is not normal. Can someone help to debug this?

**Comment by ImperatorS79** [comment]
This simply because you delete `[HKEY_CURRENT_USER\Software\Wine]`, which thus deletes `[HKEY_CURRENT_USER\Software\Wine\DllOverrides]`.

**Comment by qparis** [comment]
Ok, we should use instead: 
`[HKEY_LOCAL_MACHINE\Software\Test]
"testkey1"=-`

**Comment by ImperatorS79** [comment]
Normally everything is ready here.

**Comment by ImperatorS79** [comment]
Is it possible to check whether or not `this.uninstall("Mono")` succeed ? I mean, if mono is already uninstalled, We do not want to delete the registry key.

**Comment by plata** [comment]
There`s a check in `Wine.prototype.uninstall` already. The only thing you need to do is change the return type of that method to boolean. After that, verify that nothing is concatenated after the `uninstall()` call in the existing scripts.

File: Engines/Wine/Verbs/Remove Mono/script.js [hunk 10]
```diff
@@ -0,0 +1,45 @@
+include(["engines", "wine", "engine", "object"]);
+include(["utils", "functions", "filesystem", "files"]);
+include(["engines", "wine", "plugins", "regedit"]);
+
+/**
+* Verb to remove mono
+* @returns {Wine} Wine object
+*/
+Wine.prototype.removemono = function () {
```
Comment (madoar) [inline Engines/Wine/Verbs/Remove Mono/script.js]: I would recommend to name the method `removeMono` and its `id`: `remove_mono`

File: Engines/Wine/Verbs/dotnet20/script.js [hunk 11]
```diff
@@ -1,43 +1,57 @@
...
 include(["engines", "wine", "plugins", "windows_version"]);
+include(["engines", "wine", "verbs", "removemono"]);
 
 /**
 * Verb to install .NET 2.0
 * @returns {Wine} Wine object
 */
 Wine.prototype.dotnet20 = function () {
+    var osVersion = this.windowsVersion();
+    if (osVersion == null)
```
Comment (madoar) [inline Engines/Wine/Verbs/dotnet20/script.js]: I would recommend to add a `{` and `}` around the if-then body. This makes it easier to read and prevents errors.

File: Engines/Wine/Verbs/Remove Mono/script.js (hunk 10 above)
Comment (ImperatorS79) [reply Engines/Wine/Verbs/Remove Mono/script.js]: an id cannot contain an _.

Comment (madoar) [reply Engines/Wine/Verbs/Remove Mono/script.js]: Are you sure? What about:

https://github.com/PhoenicisOrg/scripts/blob/92fe6100542f3919e09cfd0de61575cee542cda9/Engines/Wine/Verbs/dotnet20/script.js#L5
 
and

https://github.com/PhoenicisOrg/scripts/blob/92fe6100542f3919e09cfd0de61575cee542cda9/Engines/Wine/Plugins/Windows%20version/script.json#L3

Comment (ImperatorS79) [reply Engines/Wine/Verbs/Remove Mono/script.js]: OK, I remembered codacy complaining about a _ somewhere. So if it is not the id , it was certainly the method name ^^.

**Comment by Zemogiter** [comment]
Please check codacy.

File: Engines/Wine/Verbs/Remove Mono/script.js (hunk 10 above)
Comment (plata) [reply Engines/Wine/Verbs/Remove Mono/script.js]: We should have a documentation about this.

File: Engines/Wine/Verbs/dotnet20/script.js (hunk 11 above)
Comment (plata) [reply Engines/Wine/Verbs/dotnet20/script.js]: If Codacy doesn't complain about this, we should configure it to do so.

**Comment by ImperatorS79** [comment]
If the checks are good, I do not personally see any more problems with this.

File: Engines/Wine/Verbs/dotnet20/script.js [hunk 12]
```diff
@@ -1,43 +1,55 @@
...
-        var setupFile = new Resource()
+        var setupFile64 = new Resource()
             .wizard(this.wizard())
             .url("https://download.microsoft.com/download/a/3/f/a3f1bf98-18f3-4036-9b68-8e6de530ce0a/NetFx64.exe")
             .checksum("e59cca309463a5d98daeaada83d1b05fed5126c5")
             .name("NetFx64.exe")
             .get();
-        this.uninstall("Mono");
+
+        this.remove_mono();
```
Comment (madoar) [inline Engines/Wine/Verbs/dotnet20/script.js]: Not `this.removeMono();`?

Comment (Zemogiter) [reply Engines/Wine/Verbs/dotnet20/script.js]: Correct.

**Comment by ImperatorS79** [comment]
I do not manage to fix the conflicts by following the command line instructions, so if anyone more experienced could try, that would be great.

**Comment by plata** [comment]
Normally, if you merge master this should solve the conflicts.

**Comment by ImperatorS79** [comment]
This would lead to conflicts.

**Comment by plata** [comment]
Sure, you need to resolve the conflicts during the merge.

**Comment by ImperatorS79** [comment]
And I do not know how to do it ^^.

**Comment by plata** [comment]
https://git-scm.com/docs/git-merge

Basically:
```
git merge master
git mergetool -t meld
git commit
```

**Comment by ImperatorS79** [comment]
Where ? In my local repo ? On the dotnet branch ? How to I keep what I have committed ?

**Comment by Zemogiter** [comment]
What I do is just click on the "Resolve confilcts" button on the website and manually remove conflicts.

**Comment by ImperatorS79** [comment]
This button is greyed because "conflicts are too complex" -_-'.

**Comment by Zemogiter** [comment]
lol how could a couple of lines be too complex?

**Comment by ImperatorS79** [comment]
¯\_(ツ)_/¯

**Comment by Zemogiter** [comment]
I found this. Not sure if it helps though:
https://ashfurrow.com/blog/resolving-github-merge-conflicts/

**Comment by plata** [comment]
@ImperatorS79 in your local clone with the branch you used to create the PR (you master branch needs to be up to date of course).

**Comment by ImperatorS79** [comment]
Hoping nothing else must be changed ^^.

**Comment by plata** [comment]
Some of the files changed from 644 to 755. Is that on purpose?

**Comment by ImperatorS79** [comment]
Really ? I did not modified any permission on my pc.

**Comment by plata** [comment]
At least the diff says so...
