### PR TITLE
Return Github "version" Objects instead of the tag Strings

### LINKED ISSUE #1148: Change GitHub releases utility
see https://github.com/PhoenicisOrg/scripts/blob/master/Utils/Functions/Net/GithubReleases/script.js

The approach is wrong. Some scripts assumes that the download URL is formed in a certain way based on the release version. It would be better to return the complete json and then use `tarball_url` directly.

My suggestion would be to replace
```Javascript
const versions = JSON.parse(cat(releasesFile)).map(version => version.tag_name);
```
by
```Javascript
const versions = JSON.parse(cat(releasesFile));
```

### PR DESCRIPTION
**Pull request by madoar**
This PR fixes #1148

### CODE REVIEW

**Comment by madoar** [comment]
@Zemogiter can you please give this PR a try? I couldn't test it yet

File: Engines/Wine/Verbs/D9VK/script.js [hunk 1]
```diff
@@ -28,6 +28,16 @@ class D9VK {
...
 
+    selectGithubVersion(wizard) {
+        const versions = fetchGithubReleases("Joshua-Ashton", "d9vk", wizard);
+
+        if (!this.d9vkVersion || typeof this.d9vkVersion !== 'string') {
+            return versions[0];
+        } else {
+            return versions.find(version => version.name === this.d9vkVersion);
+        }
+    }
```
Comment (madoar) [inline Engines/Wine/Verbs/D9VK/script.js]: I'm a friend of such utility functions. The only issue I have with it is that we have it multiple times in our codebase. @plata do you have any idea how to improve on this?

File: Engines/Wine/Verbs/D9VK/script.js [hunk 2]
```diff
@@ -28,6 +28,16 @@ class D9VK {
         return this;
     }
 
+    selectGithubVersion(wizard) {
```
Comment (madoar) [inline Engines/Wine/Verbs/D9VK/script.js]: `wizard` is purely for cosmetic reason here. It is not really required and could be replaced by `this.wine.wizard()`

File: Engines/Wine/Verbs/D9VK/script.js [hunk 3]
```diff
@@ -55,35 +64,24 @@ class D9VK {
...
+        var setupFile = this.downloadGithubRelease(selectedVersion, wizard);
 
         new Extractor()
             .wizard(wizard)
             .archive(setupFile)
             .to(`${prefixDirectory}/TMP/`)
             .extract();
 
-        const d9vkTmpDir = `${prefixDirectory}/TMP/d9vk-${this.d9vkVersion}`;
+        const d9vkTmpDir = `${prefixDirectory}/TMP/d9vk-${selectedVersion.name}`;
```
Comment (madoar) [inline Engines/Wine/Verbs/D9VK/script.js]: We have this pattern in multiple places and I don't like it. The version name should not be needed in the folder names in my opinion, especially because we have no "safe" method to fetch it. Who guarantees that `name` or `tag_name` contains the correct version name?

File: Engines/Wine/Verbs/D9VK/script.js [hunk 4]
```diff
@@ -115,8 +113,10 @@ class D9VK {
...
 
-        const versions = getGithubReleases("Joshua-Ashton", "d9vk", wizard);
-        const selectedVersion = wizard.menu(tr("Please select the version."), versions, versions[0]);
+        const versions = fetchGithubReleases("Joshua-Ashton", "d9vk", wizard);
+        const versionStrings = extractGithubReleaseStrings(versions);
+
+        const selectedVersion = wizard.menu(tr("Please select the version."), versionStrings, versionStrings[0]);
 
         // install selected version
         new D9VK(wine).withVersion(selectedVersion.text).go();
```
Comment (madoar) [inline Engines/Wine/Verbs/D9VK/script.js]: Should we continue to pass a `string` as the version to the verb or should we pass a `version` object?
An disadvantage of passing a `version` object is that it is github specific.

File: Utils/Functions/Net/GithubReleases/script.js [hunk 5]
```diff
@@ -1,29 +1,41 @@
...
+ * Fetches an array of tag corresponding to the releases in a git repository
  *
  * @param {string} repositoryOwner owner of the repository
  * @param {string} repositoryName name of the repository
  * @param {wizard} wizard the wizard
- * @returns {string[]} list of version tag in the repository
+ * @returns {object[]} list of version objects in the repository
  */
-module.getGithubReleases = function getGithubReleases(repositoryOwner, repositoryName, wizard) {
+module.fetchGithubReleases = function fetchGithubReleases(repositoryOwner, repositoryName, wizard) {
```
Comment (madoar) [inline Utils/Functions/Net/GithubReleases/script.js]: I have renamed the method to `fetchGithubReleases` because I think it is more fitting.

File: Utils/Functions/Net/GithubReleases/script.js [hunk 6]
```diff
@@ -1,29 +1,41 @@
...
+module.extractGithubReleaseStrings = function extractGithubReleaseStrings(versions) {
+    return versions.map(version => version.name);
+}
+
+module.downloadGithubRelease = function downloadGithubRelease(version, wizard) {
+    return new Resource()
+        .wizard(wizard)
+        .url(version.tarball_url)
+        // TODO: generate a more "random" name to prevent file conflicts
+        .name(`${version.name}.tar.xz`)
```
Comment (madoar) [inline Utils/Functions/Net/GithubReleases/script.js]: I don't like the file name. Ideally I think we should somehow generate a random filename here. @plata any ideas?

File: Utils/Functions/Net/GithubReleases/script.js [hunk 7]
```diff
@@ -1,29 +1,41 @@
...
+    const versions = JSON.parse(cat(releasesFile));
 
     remove(tmpDir);
 
     return versions;
 };
+
+module.extractGithubReleaseStrings = function extractGithubReleaseStrings(versions) {
+    return versions.map(version => version.name);
+}
```
Comment (madoar) [inline Utils/Functions/Net/GithubReleases/script.js]: Do we need to method?

**Comment by Zemogiter** [comment]
@madoar got this error when installing D9VK on `The Sims 4` wineprefix:
```
(java:5110): Gdk-WARNING **: 18:33:22.894: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
NOTE: Wine version should be greater or equal to 3.10
[INFO ] org.phoenicis.tools.archive.Tar (l.56) - Uncompressing /home/jonasz/.Phoenicis/resources/Version 0.40.1 - Croakacola Zero 🥤0️⃣🐸.tar.xz to dir /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP.
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd.
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/.github.
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/.github/ISSUE_TEMPLATE.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/.github/ISSUE_TEMPLATE/bug_report.md (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/.gitlab-ci.yml (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/LICENSE (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/README.md (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/RELEASE (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/build-win32.txt (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/build-win64.txt (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/build-wine32.txt (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/build-wine64.txt (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/dxvk.conf (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include.
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/openvr.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/openvr/LICENSE (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/openvr/openvr.hpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/spirv.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/spirv/GLSL.std.450.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/spirv/GLSL.std.450.hpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/spirv/spirv.hpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/vulkan.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/vulkan/vk_platform.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/vulkan/vulkan.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/vulkan/vulkan_core.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/include/vulkan/vulkan_win32.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/lib.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/lib/d3dcompiler_43.lib (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/lib/libd3dcompiler_43.def (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/lib/vulkan-1.lib (509).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/lib32.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/lib32/d3dcompiler_43.lib (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/lib32/libd3dcompiler_43.def (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/lib32/vulkan-1.lib (509).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/meson_options.txt (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/package-release.sh (509).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/setup_dxvk.sh (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src.
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10.def (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10.spec (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_1.def (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_1.spec (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_blend.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_blend.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_buffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_buffer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_depth_stencil.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_depth_stencil.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_device.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_device.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_include.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_input_layout.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_input_layout.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_main.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_multithread.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_multithread.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_query.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_query.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_rasterizer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_rasterizer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_reflection.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_reflection.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_sampler.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_sampler.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_shader.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_state_block.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_state_block.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_texture.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_texture.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_util.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_util.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_view_dsv.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_view_dsv.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_view_rtv.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_view_rtv.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_view_srv.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10_view_srv.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10core.def (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/d3d10core.spec (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/version10.rc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/version10_1.rc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d10/version10_core.rc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11.def (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11.spec (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_annotation.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_annotation.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_blend.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_blend.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_buffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_buffer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_class_linkage.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_class_linkage.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_cmd.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_cmdlist.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_cmdlist.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_context.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_context.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_context_def.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_context_def.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_context_ext.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_context_ext.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_context_imm.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_context_imm.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_context_state.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_depth_stencil.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_depth_stencil.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_device.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_device.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_device_child.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_enums.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_enums.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_gdi.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_gdi.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_include.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_initializer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_initializer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_input_layout.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_input_layout.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_interfaces.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_interop.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_interop.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_main.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_options.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_options.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_query.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_query.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_rasterizer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_rasterizer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_resource.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_resource.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_sampler.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_sampler.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_shader.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_shader.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_state.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_state.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_state_object.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_state_object.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_swapchain.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_swapchain.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_texture.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_texture.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_util.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_util.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_view.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_view_dsv.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_view_dsv.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_view_rtv.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_view_rtv.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_view_srv.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_view_srv.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_view_uav.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/d3d11_view_uav.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d11/version.rc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9.def (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9.spec (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_adapter.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_adapter.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_buffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_buffer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_caps.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_common_buffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_common_buffer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_common_texture.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_common_texture.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_constant_layout.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_constant_set.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_cursor.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_cursor.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_device.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_device.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_device_child.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_fixed_function.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_fixed_function.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_format.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_format.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_format_helpers.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_format_helpers.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_hud.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_hud.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_include.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_initializer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_initializer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_interface.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_interface.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_main.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_monitor.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_monitor.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_multithread.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_multithread.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_names.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_names.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_options.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_options.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_query.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_query.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_resource.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_sampler.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_sampler.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_shader.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_shader.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_shader_permutations.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_shader_validator.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_spec_constants.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_state.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_stateblock.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_stateblock.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_subresource.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_surface.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_surface.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_swapchain.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_swapchain.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_swvp_emu.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_swvp_emu.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_texture.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_texture.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_util.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_util.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_vertex_declaration.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_vertex_declaration.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_volume.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/d3d9_volume.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/shaders.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/shaders/d3d9_convert_yuy2_uyvy.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/shaders/d3d9_presenter_frag.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/shaders/d3d9_presenter_vert.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/d3d9/version.rc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_analysis.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_analysis.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_chunk_isgn.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_chunk_isgn.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_chunk_shex.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_chunk_shex.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_common.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_common.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_compiler.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_compiler.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_decoder.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_decoder.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_defs.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_defs.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_enums.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_header.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_header.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_include.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_modinfo.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_module.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_module.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_names.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_names.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_options.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_options.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_reader.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_reader.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_tag.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_util.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/dxbc_util.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxbc/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi.def (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi.spec (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_adapter.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_adapter.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_enums.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_enums.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_factory.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_factory.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_format.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_format.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_include.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_interfaces.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_main.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_monitor.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_monitor.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_object.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_options.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_options.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_output.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_output.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_swapchain.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/dxgi_swapchain.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/shaders.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/shaders/dxgi_presenter_frag.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/shaders/dxgi_presenter_vert.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxgi/version.rc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_analysis.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_analysis.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_code.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_code.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_common.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_common.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_compiler.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_compiler.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_ctab.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_ctab.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_decoder.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_decoder.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_enums.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_enums.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_header.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_header.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_helpers.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_include.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_isgn.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_modinfo.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_module.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_module.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_options.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_options.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_reader.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_reader.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_tables.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_tables.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_util.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/dxso_util.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxso/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_adapter.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_adapter.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_barrier.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_barrier.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_bind_mask.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_buffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_buffer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_cmdlist.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_cmdlist.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_compute.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_compute.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_constant_state.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_context.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_context.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_context_state.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_cs.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_cs.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_data.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_data.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_descriptor.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_descriptor.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_device.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_device.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_device_filter.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_device_filter.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_device_info.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_extension_provider.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_extensions.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_extensions.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_format.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_format.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_framebuffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_framebuffer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_gpu_event.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_gpu_event.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_gpu_query.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_gpu_query.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_graphics.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_graphics.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_graphics_state.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_hash.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_image.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_image.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_include.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_instance.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_instance.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_lifetime.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_lifetime.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_limits.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_main.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_main.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_memory.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_memory.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_blit.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_blit.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_clear.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_clear.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_copy.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_copy.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_mipgen.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_mipgen.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_pack.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_pack.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_resolve.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_meta_resolve.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_objects.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_openvr.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_openvr.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_options.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_options.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_pipecache.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_pipecache.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_pipelayout.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_pipelayout.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_pipemanager.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_pipemanager.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_platform_exts.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_queue.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_queue.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_recycler.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_renderpass.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_renderpass.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_resource.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_resource.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_sampler.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_sampler.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_shader.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_shader.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_shader_key.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_shader_key.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_signal.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_signal.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_spec_const.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_spec_const.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_staging.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_staging.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_state_cache.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_state_cache.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_state_cache_types.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_stats.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_stats.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_unbound.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_unbound.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_util.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/dxvk_util.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/dxvk_hud.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/dxvk_hud.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/dxvk_hud_font.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/dxvk_hud_font.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/dxvk_hud_item.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/dxvk_hud_item.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/dxvk_hud_renderer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/dxvk_hud_renderer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/shaders.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/shaders/hud_line_frag.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/shaders/hud_line_vert.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/shaders/hud_text_frag.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/hud/shaders/hud_text_vert.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/platform.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/platform/dxvk_win32_exts.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_blit_frag_1d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_blit_frag_2d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_blit_frag_3d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_buffer_f.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_buffer_u.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image1d_f.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image1d_u.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image1darr_f.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image1darr_u.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image2d_f.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image2d_u.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image2darr_f.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image2darr_u.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image3d_f.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_clear_image3d_u.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_copy_color_1d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_copy_color_2d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_copy_color_ms.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_copy_depth_1d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_copy_depth_2d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_copy_depth_ms.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_copy_depth_stencil_1d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_copy_depth_stencil_2d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_copy_depth_stencil_ms.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_fullscreen_geom.geom (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_fullscreen_layer_vert.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_fullscreen_vert.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_pack_d24s8.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_pack_d32s8.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_resolve_frag_d.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_resolve_frag_ds.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_resolve_frag_f.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_resolve_frag_f_amd.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_resolve_frag_i.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_resolve_frag_u.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_unpack_d24s8.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_unpack_d24s8_as_d32s8.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/dxvk/shaders/dxvk_unpack_d32s8.comp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv/spirv_code_buffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv/spirv_code_buffer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv/spirv_compression.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv/spirv_compression.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv/spirv_include.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv/spirv_instruction.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv/spirv_module.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/spirv/spirv_module.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util.
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/com.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/com/com_guid.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/com/com_guid.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/com/com_include.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/com/com_object.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/com/com_pointer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/com/com_private_data.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/com/com_private_data.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/config.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/config/config.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/config/config.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/log.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/log/log.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/log/log.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/log/log_debug.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/log/log_debug.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/rc.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/rc/util_rc.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/rc/util_rc_ptr.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sha1.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sha1/sha1.c (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sha1/sha1.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sha1/sha1_util.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sha1/sha1_util.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sync.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sync/sync_signal.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sync/sync_signal_win32.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sync/sync_spinlock.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/sync/sync_ticketlock.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/thread.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_bit.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_enum.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_env.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_env.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_error.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_flags.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_gdi.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_gdi.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_lazy.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_likely.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_luid.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_luid.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_math.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_matrix.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_matrix.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_misc.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_ratio.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_string.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_string.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_time.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/util/util_vector.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan/vulkan_loader.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan/vulkan_loader.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan/vulkan_loader_fn.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan/vulkan_names.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan/vulkan_names.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan/vulkan_presenter.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan/vulkan_presenter.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/src/vulkan/vulkan_util.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests.
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d11.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d11/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d11/test_d3d11_compute.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d11/test_d3d11_formats.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d11/test_d3d11_map_read.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d11/test_d3d11_streamout.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d11/test_d3d11_triangle.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d9.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d9/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d9/test_d3d9_buffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d9/test_d3d9_clear.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/d3d9/test_d3d9_triangle.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/dxbc.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/dxbc/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/dxbc/test_dxbc_compiler.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/dxbc/test_dxbc_disasm.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/dxbc/test_hlsl_compiler.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/dxgi.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/dxgi/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/dxgi/test_dxgi_factory.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/tests/test_utils.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/The Sims 4/TMP/Joshua-Ashton-d9vk-c18e0bd/version.h.in (436).
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - Path "/home/jonasz/.Phoenicis/containers//wineprefix//The Sims 4//TMP/d9vk-Version 0.40.1 - Croakacola Zero 🥤0️⃣🐸/x32" does not exist
	at org.phoenicis.tools.files.FileUtilities.ls(FileUtilities.java:55)
	at <js> ls(Unnamed:11:330-360)
	at <js> go(Unnamed:87:3265-3287)
	at <js> install(Unnamed:122:4461-4513)
	at org.graalvm.polyglot.Value.invokeMember(Value.java:459)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:71)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: java.lang.IllegalArgumentException: Path "/home/jonasz/.Phoenicis/containers//wineprefix//The Sims 4//TMP/d9vk-Version 0.40.1 - Croakacola Zero 🥤0️⃣🐸/x32" does not exist

[WARNING] 
org.graalvm.polyglot.PolyglotException: Path "/home/jonasz/.Phoenicis/containers//wineprefix//The Sims 4//TMP/d9vk-Version 0.40.1 - Croakacola Zero 🥤0️⃣🐸/x32" does not exist
    at org.phoenicis.tools.files.FileUtilities.ls (FileUtilities.java:55)
    at <js>.ls (Unnamed:11)
    at <js>.go (Unnamed:87)
    at <js>.install (Unnamed:122)
    at org.graalvm.polyglot.Value.invokeMember (Value.java:459)
    at org.phoenicis.engines.VerbsManager.lambda$installVerb$0 (VerbsManager.java:71)
    at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval (PhoenicisInteractiveScriptSession.java:35)
    at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1 (BackgroundScriptInterpreter.java:45)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
```
Haven't tested DXVK yet.

**Comment by Zemogiter** [comment]
VK9 lacks `cp` definition.
After adding one I get this error:
```
(java:5703): Gdk-WARNING **: 18:40:08.508: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
NOTE: wine version should be greater or equal to 3.5
NOTE: works from 0.28.0
[INFO ] org.phoenicis.tools.archive.Tar (l.56) - Uncompressing /home/jonasz/.Phoenicis/resources/Release 0.29.0.tar.xz to dir /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32.
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/.gitignore (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/LICENSE.md (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/README.md (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/UpgradeLog.htm (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/BufferManager.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/BufferManager.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/C9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/C9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CBaseTexture9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CBaseTexture9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CCubeTexture9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CCubeTexture9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CDevice9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CDevice9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CIndexBuffer9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CIndexBuffer9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CPixelShader9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CPixelShader9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CQuery9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CQuery9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CRenderTargetSurface9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CRenderTargetSurface9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CResource9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CResource9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CStateBlock9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CStateBlock9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CSurface9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CSurface9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CSwapChain9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CSwapChain9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CTexture9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CTexture9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CTypes.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CTypes.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVertexBuffer9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVertexBuffer9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVertexDeclaration9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVertexDeclaration9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVertexShader9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVertexShader9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVolume9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVolume9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVolumeTexture9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/CVolumeTexture9.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/D3D9.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/DrawContext.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/DrawContext.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/GarbageManager.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/GarbageManager.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Perf_CommandStreamManager.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Perf_CommandStreamManager.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Perf_ProcessQueue.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Perf_ProcessQueue.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Perf_RenderManager.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Perf_RenderManager.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Perf_StateManager.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Perf_StateManager.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/PrivateTypes.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealDevice.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealDevice.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealIndexBuffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealIndexBuffer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealInstance.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealInstance.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealQuery.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealQuery.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealRenderTarget.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealRenderTarget.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealSurface.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealSurface.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealSwapChain.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealSwapChain.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealTexture.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealTexture.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealVertexBuffer.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealVertexBuffer.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealWindow.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/RealWindow.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/ResourceContext.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/ResourceContext.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/SamplerRequest.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/SamplerRequest.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/ShaderConverter.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/ShaderConverter.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders.aps (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders.rc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/Constants (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/FixedFunctions (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/Functions (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/GlobalIllumination (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/PixelPassthrough.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/Structures (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZRHW.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZRHW_DIFFUSE.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZRHW_DIFFUSE_TEX1.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZRHW_DIFFUSE_TEX2.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZRHW_TEX1.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZRHW_TEX2.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_DIFFUSE.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_DIFFUSE.geom (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_DIFFUSE.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_DIFFUSE_TEX1.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_DIFFUSE_TEX1.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_DIFFUSE_TEX2.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_DIFFUSE_TEX2.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_DIFFUSE.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_DIFFUSE.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_DIFFUSE_TEX1.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_DIFFUSE_TEX1.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_DIFFUSE_TEX2.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_DIFFUSE_TEX2.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_TEX1.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_TEX1.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_TEX2.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_NORMAL_TEX2.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_TEX1.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_TEX1.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_TEX2.frag (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/VertexBuffer_XYZ_TEX2.vert (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Shaders/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/TinyQueue.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Utilities.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/Utilities.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/VK9-Library.mk (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/VK9-Library.project (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/VK9-Library.vcproj (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/VK9-Library.vcxproj (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/VK9-Library.vcxproj.filters (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/VK9-Library.vcxproj.user (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/VK9-Logo.bmp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/VK9.conf (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/WorkItem.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/WorkItemType.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/atomicops.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/d3d9.def (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/dllmain.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/pch.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/pch/stdafx.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/pch/stdafx.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/readerwriterqueue.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/renderdoc_app.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/resource.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/targetver.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Library/vk_mem_alloc.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/Main.cpp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/My Amplifier XE Results - VK9-Tests.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/My Amplifier XE Results - VK9-Tests/My Amplifier XE Results - VK9-Tests.amplxeproj (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/Resource.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.aps (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.ico (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.mk (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.project (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.rc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.vcproj (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.vcxproj (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.vcxproj.filters (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/VK9-Tests.vcxproj.user (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/pixel_shader.psh (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/small.ico (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/targetver.h (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/test.bmp (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9-Tests/vertex_shader.vsh (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/VK9.sln (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/build-win32.txt (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/build-win64.txt (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/dep32.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/dep32/boost.sh (509).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/dep32/eigen.pc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/dep32/vulkan-1.pc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/dep64.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/dep64/boost.sh (509).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/dep64/eigen.pc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/dep64/vulkan-1.pc (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/meson_options.txt (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/package-release.sh (509).
[INFO ] org.phoenicis.tools.archive.Tar (l.163) - Attempting to write output directory /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/wine_utils.
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/wine_utils/meson.build (436).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/wine_utils/setup_vk9.sh.in (509).
[INFO ] org.phoenicis.tools.archive.Tar (l.172) - Creating output file /home/jonasz/.Phoenicis/containers/wineprefix/SimCity 2013/TMP32/disks86-VK9-f0ea5f2/wine_utils/setup_vk9.verb (436).
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - Path "/home/jonasz/.Phoenicis/containers//wineprefix//SimCity 2013//drive_c/windows/syswow64" does not exist
	at org.phoenicis.tools.files.FileUtilities.copy(FileUtilities.java:139)
	at <js> cp(Unnamed:56:1251-1284)
	at <js> go(Unnamed:82:2947-3044)
	at <js> install(Unnamed:122:4449-4500)
	at org.graalvm.polyglot.Value.invokeMember(Value.java:459)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:71)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: java.lang.IllegalArgumentException: Path "/home/jonasz/.Phoenicis/containers//wineprefix//SimCity 2013//drive_c/windows/syswow64" does not exist

[WARNING] 
org.graalvm.polyglot.PolyglotException: Path "/home/jonasz/.Phoenicis/containers//wineprefix//SimCity 2013//drive_c/windows/syswow64" does not exist
    at org.phoenicis.tools.files.FileUtilities.copy (FileUtilities.java:139)
    at <js>.cp (Unnamed:56)
    at <js>.go (Unnamed:82)
    at <js>.install (Unnamed:122)
    at org.graalvm.polyglot.Value.invokeMember (Value.java:459)
    at org.phoenicis.engines.VerbsManager.lambda$installVerb$0 (VerbsManager.java:71)
    at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval (PhoenicisInteractiveScriptSession.java:35)
    at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1 (BackgroundScriptInterpreter.java:45)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
```
But that directory does exist, obviously.

**Comment by Zemogiter** [comment]
Galium9 extracts into `iXit-wine-nine-standalone-de5e690` folder and the script is apparently looking into `galium-nine-standalone`

**Comment by madoar** [comment]
@Zemogiter thanks for testing!

It seems like I imagined this as easier than reality apparently is.
There are multiple issues we are stumbling across:
- `version.name` is not `version.tag_name` (which one should we show to the user?)
- `tarball_url` leads to the **source code** not to the built archive we actually want to download the built archive can be found in `version.assets`
- some releases consist of multiple downloadable files, i.e. `version.assets` is an array. In these cases we would need some kind of selection mechanism, which would be really ugly. 

I'm actually unsure how far we should go automating this, because a lot of patterns we currently assume to be consistent over all releases may possible change between releases and/or repositories in reality. 

If you want to take a look at the format we need to work with take a look at the following [example](https://api.github.com/repos/disks86/VK9/releases)

**Comment by Zemogiter** [comment]
@madoar following VK9's example I think `version.tag_name` is a better choice because it's a simple string number with dots. `version.name` could cause issues we are seeing now.
By `version.assets` you mean this:
Zrzut ekranu z 2019-12-26 11-35-03

File: Engines/Wine/Verbs/D9VK/script.js (hunk 1 above)
Comment (plata) [reply Engines/Wine/Verbs/D9VK/script.js]: We could have something like `WizardUtils`. But honestly, I'm not sure if it makes too much sense. It would increase the complexity a bit for extracting these few lines of rather trivial code.

File: Engines/Wine/Verbs/D9VK/script.js (hunk 2 above)
Comment (plata) [reply Engines/Wine/Verbs/D9VK/script.js]: We should decide how we handle these cases in general. In my opinion, we should not pass parameters which are not required.

File: Engines/Wine/Verbs/D9VK/script.js (hunk 3 above)
Comment (plata) [reply Engines/Wine/Verbs/D9VK/script.js]: Yes, also it does not seem to be required at all.

File: Engines/Wine/Verbs/D9VK/script.js (hunk 4 above)
Comment (plata) [reply Engines/Wine/Verbs/D9VK/script.js]: `string`. Otherwise you can never write something like `withVersion("2.3")`.

File: Utils/Functions/Net/GithubReleases/script.js (hunk 6 above)
Comment (plata) [reply Utils/Functions/Net/GithubReleases/script.js]: Why not make the interface similar to `Downloader`?

File: Utils/Functions/Net/GithubReleases/script.js (hunk 7 above)
Comment (plata) [reply Utils/Functions/Net/GithubReleases/script.js]: Is it used? I have no clue.

File: Utils/Functions/Net/GithubReleases/script.js [hunk 8]
```diff
@@ -1,29 +1,41 @@
...
+
+module.downloadGithubRelease = function downloadGithubRelease(version, wizard) {
```
Comment (plata) [inline Utils/Functions/Net/GithubReleases/script.js]: Couldn't this be
```Javascript
module.downloadGithubRelease = function (version, wizard) {
```
?

File: Engines/Wine/Verbs/D9VK/script.js (hunk 4 above)
Comment (madoar) [reply Engines/Wine/Verbs/D9VK/script.js]: The issue with passing a string is that it is misleading in my opinion. The reason is that it is unclear what the version string for a github release is. Is it `tag_name`, `name`, `id` or some other value of the version?

File: Utils/Functions/Net/GithubReleases/script.js (hunk 6 above)
Comment (madoar) [reply Utils/Functions/Net/GithubReleases/script.js]: You mean change it to a class?

File: Utils/Functions/Net/GithubReleases/script.js (hunk 7 above)
Comment (madoar) [reply Utils/Functions/Net/GithubReleases/script.js]: It is currently but it is just a one-liner. It does not really add anything. In some cases it may also be a bad choice because `version.name` can contain the "wrong" release version string.

File: Utils/Functions/Net/GithubReleases/script.js (hunk 8 above)
Comment (madoar) [reply Utils/Functions/Net/GithubReleases/script.js]: Yes

**Comment by madoar** [comment]
@Zemogiter almost. As far as I understand the API `version.assets` would only contain the information for `dxvk-1.5.tar.gz`, the other two files are linked to in the `tarball_url` field and in a second field

**Comment by Zemogiter** [comment]
@madoar then in every case we are using `getGithubReleases` (DXVK,D9VK,Gallium9,VK9,FAudio) `version.assets` contains just one file. Let's use this for now. We can return to this at a later date once a need for a verb with array `version.assets` arise.

File: Utils/Functions/Net/GithubReleases/script.js (hunk 6 above)
Comment (plata) [reply Utils/Functions/Net/GithubReleases/script.js]: Yes, maybe `GitHubDownloader` and then similar methods to `Downloader`. Would that make sense to you?

File: Engines/Wine/Verbs/D9VK/script.js (hunk 4 above)
Comment (plata) [reply Engines/Wine/Verbs/D9VK/script.js]: That should be internal knowledge to the verb. The user should not have to bother about it (when calling `withVersion`).

**Comment by madoar** [comment]
> And since VK9 isn't used anywhere I think we can ignore it for now.

I'm not sure ignoring this issue is a good idea. We already know that there are repositories that provide multiple downloads for their releases (e.g. VK9), so we can be sure that we will face this issue sooner or later. If we ignore this now we will have a lot more work to change it later, because at that time we need to change all the code that depends on the then current implementation.

File: Engines/Wine/Verbs/D9VK/script.js (hunk 1 above)
Comment (madoar) [reply Engines/Wine/Verbs/D9VK/script.js]: I have deleted the methods because they don't seem to be necessary any more

File: Engines/Wine/Verbs/D9VK/script.js (hunk 3 above)
Comment (madoar) [reply Engines/Wine/Verbs/D9VK/script.js]: These folder names seem to be dependent on the content of the downloaded archives. I don't think we can replace them with a real temporary directory.

File: Utils/Functions/Net/GithubReleases/script.js (hunk 6 above)
Comment (madoar) [reply Utils/Functions/Net/GithubReleases/script.js]: Done

**Comment by madoar** [comment]
@Zemogiter can you please try again? :)

**Comment by Zemogiter** [comment]
DXVK, D9VK, FAudio and galium9 displays this error before the verb displays the wizard:
```
Error while including script: "utils.functions.net.githubreleases"
	at org.phoenicis.scripts.engine.injectors.IncludeInjector.lambda$injectInto$0(IncludeInjector.java:65)
	at <js> :=>(Unnamed:8:479-523)
	at org.graalvm.polyglot.Value.execute(Value.java:368)
	at org.phoenicis.scripts.engine.injectors.IncludeInjector.lambda$injectInto$0(IncludeInjector.java:57)
	at <js> :program(Unnamed:1:0-33)
	at org.graalvm.polyglot.Context.eval(Context.java:370)
	at org.phoenicis.scripts.engine.implementation.PolyglotScriptEngine.evalAndReturn(PolyglotScriptEngine.java:73)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: org.phoenicis.scripts.exceptions.IncludeException: Error while including script: "utils.functions.net.githubreleases"
```
Terminal log:
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in unnamed module of loader java.net.URLClassLoader @7c1812b3)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:68)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[WARNING] 
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in unnamed module of loader java.net.URLClassLoader @7c1812b3)
    at org.phoenicis.engines.VerbsManager.lambda$installVerb$0 (VerbsManager.java:68)
    at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval (PhoenicisInteractiveScriptSession.java:35)
    at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1 (BackgroundScriptInterpreter.java:45)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in unnamed module of loader java.net.URLClassLoader @7c1812b3)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:68)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[WARNING] 
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in unnamed module of loader java.net.URLClassLoader @7c1812b3)
    at org.phoenicis.engines.VerbsManager.lambda$installVerb$0 (VerbsManager.java:68)
    at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval (PhoenicisInteractiveScriptSession.java:35)
    at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1 (BackgroundScriptInterpreter.java:45)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Render target lock mode", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Strict Draw Ordering", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "GLSL support", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Always offscreen", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "DirectDraw renderer", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Offscreen rendering mode", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Video memory size", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "UseTakeFocus", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Retina support", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Mouse warp override", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Multisampling", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Fonts Smoothing", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Render target lock mode", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Strict Draw Ordering", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "GLSL support", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Always offscreen", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "DirectDraw renderer", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Offscreen rendering mode", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Video memory size", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "UseTakeFocus", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Retina support", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Mouse warp override", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Multisampling", will use default.
[WARN ] org.phoenicis.javafx.components.container.skin.ContainerEngineSettingsPanelSkin (l.96) - Could not fetch current option for engine setting "Fonts Smoothing", will use default.
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in unnamed module of loader java.net.URLClassLoader @7c1812b3)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:68)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[WARNING] 
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in unnamed module of loader java.net.URLClassLoader @7c1812b3)
    at org.phoenicis.engines.VerbsManager.lambda$installVerb$0 (VerbsManager.java:68)
    at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval (PhoenicisInteractiveScriptSession.java:35)
    at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1 (BackgroundScriptInterpreter.java:45)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in unnamed module of loader java.net.URLClassLoader @7c1812b3)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:68)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[WARNING] 
java.lang.ClassCastException: class java.lang.String cannot be cast to class org.graalvm.polyglot.Value (java.lang.String is in module java.base of loader 'bootstrap'; org.graalvm.polyglot.Value is in unnamed module of loader java.net.URLClassLoader @7c1812b3)
    at org.phoenicis.engines.VerbsManager.lambda$installVerb$0 (VerbsManager.java:68)
    at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval (PhoenicisInteractiveScriptSession.java:35)
    at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1 (BackgroundScriptInterpreter.java:45)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
```

**Comment by madoar** [comment]
Can you please try again? If it still does not work please also add which script/verb fails.

**Comment by Zemogiter** [comment]
D9VK crashes upon `fetching versions list...` with this error message:
```
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - TypeError: Cannot read property 'getReleases' of undefined
	at <js> install(Unnamed:116:4098-4125)
	at org.graalvm.polyglot.Value.invokeMember(Value.java:459)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:71)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

[WARNING] 
org.graalvm.polyglot.PolyglotException: TypeError: Cannot read property 'getReleases' of undefined
    at <js>.install (Unnamed:116)
    at org.graalvm.polyglot.Value.invokeMember (Value.java:459)
    at org.phoenicis.engines.VerbsManager.lambda$installVerb$0 (VerbsManager.java:71)
    at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval (PhoenicisInteractiveScriptSession.java:35)
    at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1 (BackgroundScriptInterpreter.java:45)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
```

**Comment by madoar** [comment]
Ups `fetchReleases()` returned void. 
The problem should be fixed. Can you try again? :)

**Comment by Zemogiter** [comment]
D9VK, FAudio and gallium9 installation works. VK9 needs this line:
```
const { cp } = include("utils.functions.filesystem.files");
```

**Comment by plata** [comment]
This PR has conflicts.

**Comment by madoar** [comment]
@Zemogiter thanks for telling me! I've added the missing includes. You can try again now.
@plata I've rebased the PR.

**Comment by plata** [comment]
Now Codacy complains.

**Comment by Zemogiter** [comment]
VK9 now also works. As for DXVK see https://github.com/PhoenicisOrg/scripts/pull/1039#issuecomment-569516175

File: Utils/Functions/Net/GithubReleases/script.js [hunk 9]
```diff
@@ -1,29 +1,90 @@
...
+        return this;
+    }
 
-    remove(tmpDir);
+    /**
+     * Fetches the GitHub releases
+     *
+     * @returns {void}
+     */
+    fetchReleases() {
```
Comment (plata) [inline Utils/Functions/Net/GithubReleases/script.js]: Shouldn't this method also return the releases?

**Comment by madoar** [comment]
@Zemogiter you need to change this line:

https://github.com/PhoenicisOrg/scripts/blob/82fe970d9cb32b2e1b179edd440468e094fb9f04/Engines/Wine/Verbs/DXVK/script.js#L80

to

```javascript
const dxvkTmpDir = `${prefixDirectory}/TMP/dxvk-${this.dxvkVersion.substring(1)}`;
```

The issue is that the author of `dxvk` doesn't seem to use the tag for its archived folder.
There is nothing that we can do in this case except removing the additional character from the selected tag_name. This is done by `.substring(1)`

**Comment by Zemogiter** [comment]
@madoar thanks
