### PR TITLE
Update vcrun6sp6 Wine Verb (fix cab extract)

### LINKED ISSUE #1162: vcrun6sp6 crash
When attempting to remove `stdole2.dll` file the verb crashes
```
Extracting to: /home/jonasz/.Phoenicis/containers//wineprefix//Shogo//drive_c/vcrun6sp6/
Extracting cabinet: /home/jonasz/.Phoenicis/resources///Vs6sp6.exe
  extracting vcredist.exe

All done, no errors.
[ERROR] org.phoenicis.multithreading.ControlledThreadPoolExecutorService (l.64) - Path "/home/jonasz/.Phoenicis/containers//wineprefix//Shogo//drive_c/windows/system32/stdole2.dll" does not exist
	at org.phoenicis.tools.files.FileUtilities.remove(FileUtilities.java:165)
	at <js> remove(Unnamed:101:2143-2172)
	at <js> go(Unnamed:38:1348-1389)
	at <js> install(Unnamed:52:1766-1789)
	at org.graalvm.polyglot.Value.invokeMember(Value.java:459)
	at org.phoenicis.engines.VerbsManager.lambda$installVerb$0(VerbsManager.java:71)
	at org.phoenicis.scripts.session.PhoenicisInteractiveScriptSession.eval(PhoenicisInteractiveScriptSession.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$createInteractiveSession$1(BackgroundScriptInterpreter.java:45)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by host exception: java.lang.IllegalArgumentException: Path "/home/jonasz/.Phoenicis/containers//wineprefix//Shogo//drive_c/windows/system32/stdole2.dll" does not exist

[WARNING] 
org.graalvm.polyglot.PolyglotException: Path "/home/jonasz/.Phoenicis/containers//wineprefix//Shogo//drive_c/windows/system32/stdole2.dll" does not exist
    at org.phoenicis.tools.files.FileUtilities.remove (FileUtilities.java:165)
    at <js>.remove (Unnamed:101)
    at <js>.go (Unnamed:38)
```
I've looked and there really is no such file.

### PR DESCRIPTION
**Pull request by Zemogiter**
### Description
Fix #1162 
### What works
Everything
### What was not tested
Nothing
### Test
- Operating system (and linux kernel version): ubuntu 19.10
- Hardware (GPU/CPU): gtx 1080 ti, i7-7700K

### Ready for review
- [x] Script tested as a regular phoenicis user and working (if you have a problem -> create as draft and ask for help).
- [x] `json-align` and `eslint` run according to the [documentation](https://phoenicisorg.github.io/scripts/General/tools/). 
- [x] Codacy and travis checked.

### CODE REVIEW

File: Engines/Wine/Verbs/vcrun6sp6/script.js [hunk 1]
```diff
@@ -39,6 +41,7 @@ class Vcrun6SP6 {
 
         wizard.wait(tr("Please wait while {0} is installed...", "vcrun6sp6"));
 
+        print("setupFile: " + setupFile);
```
Comment (madoar) [inline Engines/Wine/Verbs/vcrun6sp6/script.js]: Please remove this debug print statement

File: Engines/Wine/Verbs/vcrun6sp6/script.js [hunk 2]
```diff
@@ -25,11 +25,13 @@ class Vcrun6SP6 {
...
 
-        const setupFile = new CabExtract()
+        const setupDir = `${prefixDirectory}/drive_c/vcrun6sp6/`;
+        new CabExtract()
             .wizard(wizard)
             .archive(toBeCabExtracted)
-            .to(`${prefixDirectory}/drive_c/vcrun6sp6/`)
+            .to(setupDir)
             .extract(["-L", "-F", "vcredist.exe"]);
+        const setupFile = setupDir + "vcredist.exe";
```
Comment (madoar) [inline Engines/Wine/Verbs/vcrun6sp6/script.js]: I think it may be better to move this line down to line 44

**Comment by Zemogiter** [comment]
Ready for review.
